python generate_data.py anomaly